In [98]:
import pandas as pd
import numpy as np
from math import sqrt
import scipy.optimize as sco
from numpy.random import Generator, SFC64
rg = Generator(SFC64())
import yfinance as yf
import plotly
from plotly import graph_objs as go
plotly.offline.init_notebook_mode(connected = True)

In [2]:
# Define asset returns and variance
mu1 = 0.08
sig1 = 0.30

mu2 = 0.14
sig2 = 0.40

# Perfectly Correlated

In [21]:
def sigp(w1):
    p_var = (w1**2)*sig1 + 2*p*(1-w1)*w1*sqrt(sig1)*sqrt(sig2) + ((1-w1)**2)*sig2
    return p_var

def mup(w1):
    return w1*mu1 + (1-w1)*mu2

p = 1
w1 = 1
perf_df = pd.DataFrame({'Weight 1': w1*100, 'µ1': mu1*100, 'Variance 1': sig1*100, \
                   'Weight 2': (1 - w1)*100, 'µ2': mu2*100, 'Variance 2': sig2*100, \
                  'Variance P': sigp(w1)*100, 'µP': mup(w1)*100}, index = [0])
for i in np.linspace(0.01,1,100):
    temp = w1 - i
    perf_df = perf_df.append({'Weight 1': temp*100, 'µ1': mu1*100, 'Variance 1': sig1*100, \
                   'Weight 2': (1 - temp)*100, 'µ2': mu2*100, 'Variance 2': sig2*100, \
                  'Variance P': sigp(temp)*100, 'µP': mup(temp)*100}, ignore_index = True)
    
perf_df

Weight 1   µ1  Variance 1  Weight 2    µ2  Variance 2  Variance P     µP
0       100.0  8.0        30.0       0.0  14.0        40.0   30.000000   8.00
1        99.0  8.0        30.0       1.0  14.0        40.0   30.092892   8.06
2        98.0  8.0        30.0       2.0  14.0        40.0   30.185928   8.12
3        97.0  8.0        30.0       3.0  14.0        40.0   30.279107   8.18
4        96.0  8.0        30.0       4.0  14.0        40.0   30.372430   8.24
5        95.0  8.0        30.0       5.0  14.0        40.0   30.465897   8.30
6        94.0  8.0        30.0       6.0  14.0        40.0   30.559507   8.36
7        93.0  8.0        30.0       7.0  14.0        40.0   30.653260   8.42
8        92.0  8.0        30.0       8.0  14.0        40.0   30.747158   8.48
9        91.0  8.0        30.0       9.0  14.0        40.0   30.841198   8.54
10       90.0  8.0        30.0      10.0  14.0        40.0   30.935383   8.60
11       89.0  8.0        30.0      11.0  14.0        40.0   31.029711   8.66
12       88.0  8.0        30.0      12.0  14.0        40.0   31.124183   8.72
13       87.0  8.0        30.0      13.0  14.0        40.0   31.218798   8.78
14       86.0  8.0        30.0      14.0  14.0        40.0   31.313557   8.84
15       85.0  8.0        30.0      15.0  14.0        40.0   31.408459   8.90
16       84.0  8.0        30.0      16.0  14.0        40.0   31.503505   8.96
17       83.0  8.0        30.0      17.0  14.0        40.0   31.598695   9.02
18       82.0  8.0        30.0      18.0  14.0        40.0   31.694028   9.08
19       81.0  8.0        30.0      19.0  14.0        40.0   31.789505   9.14
20       80.0  8.0        30.0      20.0  14.0        40.0   31.885125   9.20
21       79.0  8.0        30.0      21.0  14.0        40.0   31.980889   9.26
22       78.0  8.0        30.0      22.0  14.0        40.0   32.076797   9.32
23       77.0  8.0        30.0      23.0  14.0        40.0   32.172848   9.38
24       76.0  8.0        30.0      24.0  14.0        40.0   32.269043   9.44
25       75.0  8.0        30.0      25.0  14.0        40.0   32.365381   9.50
26       74.0  8.0        30.0      26.0  14.0        40.0   32.461863   9.56
27       73.0  8.0        30.0      27.0  14.0        40.0   32.558489   9.62
28       72.0  8.0        30.0      28.0  14.0        40.0   32.655258   9.68
29       71.0  8.0        30.0      29.0  14.0        40.0   32.752170   9.74
..        ...  ...         ...       ...   ...         ...         ...    ...
71       29.0  8.0        30.0      71.0  14.0        40.0   36.952170  12.26
72       28.0  8.0        30.0      72.0  14.0        40.0   37.055258  12.32
73       27.0  8.0        30.0      73.0  14.0        40.0   37.158489  12.38
74       26.0  8.0        30.0      74.0  14.0        40.0   37.261863  12.44
75       25.0  8.0        30.0      75.0  14.0        40.0   37.365381  12.50
76       24.0  8.0        30.0      76.0  14.0        40.0   37.469043  12.56
77       23.0  8.0        30.0      77.0  14.0        40.0   37.572848  12.62
78       22.0  8.0        30.0      78.0  14.0        40.0   37.676797  12.68
79       21.0  8.0        30.0      79.0  14.0        40.0   37.780889  12.74
80       20.0  8.0        30.0      80.0  14.0        40.0   37.885125  12.80
81       19.0  8.0        30.0      81.0  14.0        40.0   37.989505  12.86
82       18.0  8.0        30.0      82.0  14.0        40.0   38.094028  12.92
83       17.0  8.0        30.0      83.0  14.0        40.0   38.198695  12.98
84       16.0  8.0        30.0      84.0  14.0        40.0   38.303505  13.04
85       15.0  8.0        30.0      85.0  14.0        40.0   38.408459  13.10
86       14.0  8.0        30.0      86.0  14.0        40.0   38.513557  13.16
87       13.0  8.0        30.0      87.0  14.0        40.0   38.618798  13.22
88       12.0  8.0        30.0      88.0  14.0        40.0   38.724183  13.28
89       11.0  8.0        30.0      89.0  14.0        40.0   38.829711  13.34
90       10.0  8.0        3

In [42]:
def sigp2(w,sig):
    return np.dot(np.dot(w.T,sig),w)

def mup2(w,rets):
    return np.dot(w,rets)
p=1
cov = np.array(((sig1,p*np.sqrt(sig1*sig2)),(p*np.sqrt(sig1*sig2),sig2)))
rets = np.array((mu1,mu2))
weights1 = np.linspace(0,1,101)
pd.DataFrame({'Weight 1':(1-weights1)*100, 'µ1':[mu1*100]*101, 'Variance 1':[sig1*100]*101, 'Weight 2':weights1*100
              ,'µ2':[mu2*100]*101, 'Variance 2':[sig2*100]*101,
              'Variance P': [100*sigp2(np.array((1-i,i)),cov) for i in weights1],
             'µP': [100*mup2(np.array((1-i,i)),rets) for i in weights1]})

Weight 1   µ1  Variance 1  Weight 2    µ2  Variance 2  Variance P     µP
0       100.0  8.0        30.0       0.0  14.0        40.0   30.000000   8.00
1        99.0  8.0        30.0       1.0  14.0        40.0   30.092892   8.06
2        98.0  8.0        30.0       2.0  14.0        40.0   30.185928   8.12
3        97.0  8.0        30.0       3.0  14.0        40.0   30.279107   8.18
4        96.0  8.0        30.0       4.0  14.0        40.0   30.372430   8.24
5        95.0  8.0        30.0       5.0  14.0        40.0   30.465897   8.30
6        94.0  8.0        30.0       6.0  14.0        40.0   30.559507   8.36
7        93.0  8.0        30.0       7.0  14.0        40.0   30.653260   8.42
8        92.0  8.0        30.0       8.0  14.0        40.0   30.747158   8.48
9        91.0  8.0        30.0       9.0  14.0        40.0   30.841198   8.54
10       90.0  8.0        30.0      10.0  14.0        40.0   30.935383   8.60
11       89.0  8.0        30.0      11.0  14.0        40.0   31.029711   8.66
12       88.0  8.0        30.0      12.0  14.0        40.0   31.124183   8.72
13       87.0  8.0        30.0      13.0  14.0        40.0   31.218798   8.78
14       86.0  8.0        30.0      14.0  14.0        40.0   31.313557   8.84
15       85.0  8.0        30.0      15.0  14.0        40.0   31.408459   8.90
16       84.0  8.0        30.0      16.0  14.0        40.0   31.503505   8.96
17       83.0  8.0        30.0      17.0  14.0        40.0   31.598695   9.02
18       82.0  8.0        30.0      18.0  14.0        40.0   31.694028   9.08
19       81.0  8.0        30.0      19.0  14.0        40.0   31.789505   9.14
20       80.0  8.0        30.0      20.0  14.0        40.0   31.885125   9.20
21       79.0  8.0        30.0      21.0  14.0        40.0   31.980889   9.26
22       78.0  8.0        30.0      22.0  14.0        40.0   32.076797   9.32
23       77.0  8.0        30.0      23.0  14.0        40.0   32.172848   9.38
24       76.0  8.0        30.0      24.0  14.0        40.0   32.269043   9.44
25       75.0  8.0        30.0      25.0  14.0        40.0   32.365381   9.50
26       74.0  8.0        30.0      26.0  14.0        40.0   32.461863   9.56
27       73.0  8.0        30.0      27.0  14.0        40.0   32.558489   9.62
28       72.0  8.0        30.0      28.0  14.0        40.0   32.655258   9.68
29       71.0  8.0        30.0      29.0  14.0        40.0   32.752170   9.74
..        ...  ...         ...       ...   ...         ...         ...    ...
71       29.0  8.0        30.0      71.0  14.0        40.0   36.952170  12.26
72       28.0  8.0        30.0      72.0  14.0        40.0   37.055258  12.32
73       27.0  8.0        30.0      73.0  14.0        40.0   37.158489  12.38
74       26.0  8.0        30.0      74.0  14.0        40.0   37.261863  12.44
75       25.0  8.0        30.0      75.0  14.0        40.0   37.365381  12.50
76       24.0  8.0        30.0      76.0  14.0        40.0   37.469043  12.56
77       23.0  8.0        30.0      77.0  14.0        40.0   37.572848  12.62
78       22.0  8.0        30.0      78.0  14.0        40.0   37.676797  12.68
79       21.0  8.0        30.0      79.0  14.0        40.0   37.780889  12.74
80       20.0  8.0        30.0      80.0  14.0        40.0   37.885125  12.80
81       19.0  8.0        30.0      81.0  14.0        40.0   37.989505  12.86
82       18.0  8.0        30.0      82.0  14.0        40.0   38.094028  12.92
83       17.0  8.0        30.0      83.0  14.0        40.0   38.198695  12.98
84       16.0  8.0        30.0      84.0  14.0        40.0   38.303505  13.04
85       15.0  8.0        30.0      85.0  14.0        40.0   38.408459  13.10
86       14.0  8.0        30.0      86.0  14.0        40.0   38.513557  13.16
87       13.0  8.0        30.0      87.0  14.0        40.0   38.618798  13.22
88       12.0  8.0        30.0      88.0  14.0        40.0   38.724183  13.28
89       11.0  8.0        30.0      89.0  14.0        40.0   38.829711  13.34
90       10.0  8.0        3

In [144]:
trace0 = go.Scatter(
    x = perf_df['Variance P'], y = perf_df['µP'], name = 'Perfect Correlation'
)
data = [trace0]
layout = go.Layout(
    title = 'Case of a Portfolio With 2 Securities', yaxis = dict(title = 'Expected Return (%)'), 
    xaxis = dict(title = 'Standard Deviation (%)'))
fig = go.Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

# Perfectly Uncorrelated

In [142]:
p = -1
cov = np.array(((sig1,p*np.sqrt(sig1*sig2)),(p*np.sqrt(sig1*sig2),sig2)))
anti_df = pd.DataFrame({'Weight 1':(1-weights1)*100, 'µ1':[mu1*100]*101, 'Variance 1':[sig1*100]*101, 'Weight 2':weights1*100
              ,'µ2':[mu2*100]*101, 'Variance 2':[sig2*100]*101,
              'Variance P': [100*sigp2(np.array((1-i,i)),cov) for i in weights1],
             'µP': [100*mup2(np.array((1-i,i)),rets) for i in weights1]})
anti_df

Weight 1   µ1  Variance 1  Weight 2    µ2  Variance 2  Variance P     µP
0       100.0  8.0        30.0       0.0  14.0        40.0   30.000000   8.00
1        99.0  8.0        30.0       1.0  14.0        40.0   28.721108   8.06
2        98.0  8.0        30.0       2.0  14.0        40.0   27.470072   8.12
3        97.0  8.0        30.0       3.0  14.0        40.0   26.246893   8.18
4        96.0  8.0        30.0       4.0  14.0        40.0   25.051570   8.24
5        95.0  8.0        30.0       5.0  14.0        40.0   23.884103   8.30
6        94.0  8.0        30.0       6.0  14.0        40.0   22.744493   8.36
7        93.0  8.0        30.0       7.0  14.0        40.0   21.632740   8.42
8        92.0  8.0        30.0       8.0  14.0        40.0   20.548842   8.48
9        91.0  8.0        30.0       9.0  14.0        40.0   19.492802   8.54
10       90.0  8.0        30.0      10.0  14.0        40.0   18.464617   8.60
11       89.0  8.0        30.0      11.0  14.0        40.0   17.464289   8.66
12       88.0  8.0        30.0      12.0  14.0        40.0   16.491817   8.72
13       87.0  8.0        30.0      13.0  14.0        40.0   15.547202   8.78
14       86.0  8.0        30.0      14.0  14.0        40.0   14.630443   8.84
15       85.0  8.0        30.0      15.0  14.0        40.0   13.741541   8.90
16       84.0  8.0        30.0      16.0  14.0        40.0   12.880495   8.96
17       83.0  8.0        30.0      17.0  14.0        40.0   12.047305   9.02
18       82.0  8.0        30.0      18.0  14.0        40.0   11.241972   9.08
19       81.0  8.0        30.0      19.0  14.0        40.0   10.464495   9.14
20       80.0  8.0        30.0      20.0  14.0        40.0    9.714875   9.20
21       79.0  8.0        30.0      21.0  14.0        40.0    8.993111   9.26
22       78.0  8.0        30.0      22.0  14.0        40.0    8.299203   9.32
23       77.0  8.0        30.0      23.0  14.0        40.0    7.633152   9.38
24       76.0  8.0        30.0      24.0  14.0        40.0    6.994957   9.44
25       75.0  8.0        30.0      25.0  14.0        40.0    6.384619   9.50
26       74.0  8.0        30.0      26.0  14.0        40.0    5.802137   9.56
27       73.0  8.0        30.0      27.0  14.0        40.0    5.247511   9.62
28       72.0  8.0        30.0      28.0  14.0        40.0    4.720742   9.68
29       71.0  8.0        30.0      29.0  14.0        40.0    4.221830   9.74
..        ...  ...         ...       ...   ...         ...         ...    ...
71       29.0  8.0        30.0      71.0  14.0        40.0    8.421830  12.26
72       28.0  8.0        30.0      72.0  14.0        40.0    9.120742  12.32
73       27.0  8.0        30.0      73.0  14.0        40.0    9.847511  12.38
74       26.0  8.0        30.0      74.0  14.0        40.0   10.602137  12.44
75       25.0  8.0        30.0      75.0  14.0        40.0   11.384619  12.50
76       24.0  8.0        30.0      76.0  14.0        40.0   12.194957  12.56
77       23.0  8.0        30.0      77.0  14.0        40.0   13.033152  12.62
78       22.0  8.0        30.0      78.0  14.0        40.0   13.899203  12.68
79       21.0  8.0        30.0      79.0  14.0        40.0   14.793111  12.74
80       20.0  8.0        30.0      80.0  14.0        40.0   15.714875  12.80
81       19.0  8.0        30.0      81.0  14.0        40.0   16.664495  12.86
82       18.0  8.0        30.0      82.0  14.0        40.0   17.641972  12.92
83       17.0  8.0        30.0      83.0  14.0        40.0   18.647305  12.98
84       16.0  8.0        30.0      84.0  14.0        40.0   19.680495  13.04
85       15.0  8.0        30.0      85.0  14.0        40.0   20.741541  13.10
86       14.0  8.0        30.0      86.0  14.0        40.0   21.830443  13.16
87       13.0  8.0        30.0      87.0  14.0        40.0   22.947202  13.22
88       12.0  8.0        30.0      88.0  14.0        40.0   24.091817  13.28
89       11.0  8.0        30.0      89.0  14.0        40.0   25.264289  13.34
90       10.0  8.0        3

In [145]:
trace1 = go.Scatter(
    x = anti_df['Variance P'], y = anti_df['µP'], name = 'Perfect Anticorrelation'
)
data = [trace0, trace1]
layout = go.Layout(
    title = 'Case of a Portfolio With 2 Securities', yaxis = dict(title = 'Expected Return (%)'), 
    xaxis = dict(title = 'Standard Deviation (%)'))
fig = go.Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

# No Correlation

In [146]:
p = 0
cov = np.array(((sig1,p*np.sqrt(sig1*sig2)),(p*np.sqrt(sig1*sig2),sig2)))
no_df = pd.DataFrame({'Weight 1':(1-weights1)*100, 'µ1':[mu1*100]*101, 'Variance 1':[sig1*100]*101, 'Weight 2':weights1*100
              ,'µ2':[mu2*100]*101, 'Variance 2':[sig2*100]*101,
              'Variance P': [100*sigp2(np.array((1-i,i)),cov) for i in weights1],
             'µP': [100*mup2(np.array((1-i,i)),rets) for i in weights1]})
no_df

Weight 1   µ1  Variance 1  Weight 2    µ2  Variance 2  Variance P     µP
0       100.0  8.0        30.0       0.0  14.0        40.0      30.000   8.00
1        99.0  8.0        30.0       1.0  14.0        40.0      29.407   8.06
2        98.0  8.0        30.0       2.0  14.0        40.0      28.828   8.12
3        97.0  8.0        30.0       3.0  14.0        40.0      28.263   8.18
4        96.0  8.0        30.0       4.0  14.0        40.0      27.712   8.24
5        95.0  8.0        30.0       5.0  14.0        40.0      27.175   8.30
6        94.0  8.0        30.0       6.0  14.0        40.0      26.652   8.36
7        93.0  8.0        30.0       7.0  14.0        40.0      26.143   8.42
8        92.0  8.0        30.0       8.0  14.0        40.0      25.648   8.48
9        91.0  8.0        30.0       9.0  14.0        40.0      25.167   8.54
10       90.0  8.0        30.0      10.0  14.0        40.0      24.700   8.60
11       89.0  8.0        30.0      11.0  14.0        40.0      24.247   8.66
12       88.0  8.0        30.0      12.0  14.0        40.0      23.808   8.72
13       87.0  8.0        30.0      13.0  14.0        40.0      23.383   8.78
14       86.0  8.0        30.0      14.0  14.0        40.0      22.972   8.84
15       85.0  8.0        30.0      15.0  14.0        40.0      22.575   8.90
16       84.0  8.0        30.0      16.0  14.0        40.0      22.192   8.96
17       83.0  8.0        30.0      17.0  14.0        40.0      21.823   9.02
18       82.0  8.0        30.0      18.0  14.0        40.0      21.468   9.08
19       81.0  8.0        30.0      19.0  14.0        40.0      21.127   9.14
20       80.0  8.0        30.0      20.0  14.0        40.0      20.800   9.20
21       79.0  8.0        30.0      21.0  14.0        40.0      20.487   9.26
22       78.0  8.0        30.0      22.0  14.0        40.0      20.188   9.32
23       77.0  8.0        30.0      23.0  14.0        40.0      19.903   9.38
24       76.0  8.0        30.0      24.0  14.0        40.0      19.632   9.44
25       75.0  8.0        30.0      25.0  14.0        40.0      19.375   9.50
26       74.0  8.0        30.0      26.0  14.0        40.0      19.132   9.56
27       73.0  8.0        30.0      27.0  14.0        40.0      18.903   9.62
28       72.0  8.0        30.0      28.0  14.0        40.0      18.688   9.68
29       71.0  8.0        30.0      29.0  14.0        40.0      18.487   9.74
..        ...  ...         ...       ...   ...         ...         ...    ...
71       29.0  8.0        30.0      71.0  14.0        40.0      22.687  12.26
72       28.0  8.0        30.0      72.0  14.0        40.0      23.088  12.32
73       27.0  8.0        30.0      73.0  14.0        40.0      23.503  12.38
74       26.0  8.0        30.0      74.0  14.0        40.0      23.932  12.44
75       25.0  8.0        30.0      75.0  14.0        40.0      24.375  12.50
76       24.0  8.0        30.0      76.0  14.0        40.0      24.832  12.56
77       23.0  8.0        30.0      77.0  14.0        40.0      25.303  12.62
78       22.0  8.0        30.0      78.0  14.0        40.0      25.788  12.68
79       21.0  8.0        30.0      79.0  14.0        40.0      26.287  12.74
80       20.0  8.0        30.0      80.0  14.0        40.0      26.800  12.80
81       19.0  8.0        30.0      81.0  14.0        40.0      27.327  12.86
82       18.0  8.0        30.0      82.0  14.0        40.0      27.868  12.92
83       17.0  8.0        30.0      83.0  14.0        40.0      28.423  12.98
84       16.0  8.0        30.0      84.0  14.0        40.0      28.992  13.04
85       15.0  8.0        30.0      85.0  14.0        40.0      29.575  13.10
86       14.0  8.0        30.0      86.0  14.0        40.0      30.172  13.16
87       13.0  8.0        30.0      87.0  14.0        40.0      30.783  13.22
88       12.0  8.0        30.0      88.0  14.0        40.0      31.408  13.28
89       11.0  8.0        30.0      89.0  14.0        40.0      32.047  13.34
90       10.0  8.0        3

In [147]:
trace2 = go.Scatter(
    x = no_df['Variance P'], y = no_df['µP'], name = 'No Correlation'
)
data = [trace0, trace1, trace2]
layout = go.Layout(
    title = 'Case of a Portfolio With 2 Securities', yaxis = dict(title = 'Expected Return (%)'), 
    xaxis = dict(title = 'Standard Deviation (%)'))
fig = go.Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

In [154]:
sec_names = ['Coms', 'ConsD', 'ConsS', 'Enrg', 'Fin', 'Hlth', 'Indu', 'Mats', 'ReEst', 'Tech', 'Util']
ticks = ['XLC', 'XLY', 'XLP', 'XLE', 'XLF', 'XLV', 'XLI', 'XLB', 'XLRE', 'XLK', 'XLU', 'SPY']
sec_names = ['Mats', 'Coms', 'Enrg', 'Fin', 'Indu', 'Tech', 'ConsS', 'ReEst', 'Util', 'Hlth', 'ConsD']
start = '2010-01-01'
df_full = yf.download(ticks, start)['Adj Close']
df_full.head()

[*********************100%***********************]  12 of 12 completed


SPY        XLB  XLC        XLE       XLF        XLI  \
Date                                                                    
2010-01-04  91.475693  26.796858  NaN  42.554588  7.570691  22.743147   
2010-01-05  91.717857  26.883503  NaN  42.901905  7.709840  22.823448   
2010-01-06  91.782425  27.340355  NaN  43.415653  7.725299  22.871634   
2010-01-07  92.169884  27.127686  NaN  43.350548  7.890218  23.120588   
2010-01-08  92.476562  27.505762  NaN  43.632744  7.843834  23.490007   

                  XLK        XLP  XLRE        XLU        XLV        XLY  
Date                                                                     
2010-01-04  19.574120  19.949244   NaN  21.016836  26.193764  25.727346  
2010-01-05  19.548878  19.956732   NaN  20.766634  25.936880  25.821678  
2010-01-06  19.330175  19.941774   NaN  20.888355  26.202051  25.855986  
2010-01-07  19.254469  19.941774   NaN  20.793680  26.293200  26.070374  
2010-01-08  19.380644  19.874453   NaN  20.773396  26.334637  26.061798

In [155]:
df_full = df_full.pct_change()
df_full.dropna(axis = 0, inplace = True)
df_full = 100*df_full
df_full

SPY       XLB       XLC       XLE       XLF       XLI  \
Date                                                                     
2018-06-20  0.170603 -0.324852  1.241020  0.441556 -0.255934  0.068273   
2018-06-21 -0.626893 -1.063447 -0.612904 -1.851644 -0.293263 -1.255467   
2018-06-22  0.182322  1.456308  0.437648  1.995152 -0.477932  0.345500   
2018-06-25 -1.361292 -1.555041 -2.059809 -2.009327 -1.071296 -1.267041   
2018-06-26  0.221405  0.381873  0.165814  1.262920 -0.336088  0.376603   
2018-06-27 -0.828420 -0.311243 -0.872166  1.341015 -1.236414 -0.805995   
2018-06-28  0.571758  0.381608  0.997974 -0.132325  0.872527  0.140095   
2018-06-29  0.143965  0.345603 -0.121007  0.622750  0.000000  0.209843   
2018-07-02  0.213799 -0.533840  0.625897 -1.474838  0.488926  0.223397   
2018-07-03 -0.353137 -0.173127 -1.223908  0.628160 -0.898220 -0.320398   
2018-07-05  0.815796  0.867151  1.523442 -0.106242  0.226607  0.489095   
2018-07-06  0.845824  0.498618  1.580636  0.611619  0.489810  0.347674   
2018-07-09  0.900451  0.889662  0.571209  1.493316  2.287223  1.856980   
2018-07-10  0.359831  0.847874 -0.041131  0.742194 -0.366571  0.312911   
2018-07-11 -0.731445 -1.681511 -0.135190 -2.119682 -0.478291 -1.641112   
2018-07-12  0.906588  0.239438  1.569551  0.171659  0.184840  1.172096   
2018-07-13  0.078747 -0.051177 -0.154536  0.527298 -0.442816  0.517892   
2018-07-16 -0.089400 -0.802322 -0.290185 -1.153955  1.779092 -0.406758   
2018-07-17  0.404513  1.307852  0.019406 -0.397998  0.109260  0.394817   
2018-07-18  0.210384 -0.934245 -0.290973  0.066617  1.600589  1.098475   
2018-07-19 -0.377171  0.360066 -0.700397  0.026620 -1.503771 -0.040260   
2018-07-20 -0.114275 -0.410042 -0.333080 -0.345990  0.181750 -0.107334   
2018-07-23  0.185921 -0.548971  0.412824 -0.440636  1.378818 -0.617952   
2018-07-24  0.503224  1.293770  0.704762  1.260736  0.286336  0.419031   
2018-07-25  0.852253  0.783376  0.719297  0.834418  0.214131  1.521052   
2018-07-26 -0.235916  0.574518 -3.771476  1.090250 -0.035621  0.769029   
2018-07-27 -0.677646 -0.369639 -1.897460 -0.428796  0.213750  0.013157   
2018-07-30 -0.522344 -0.185485 -1.574333  0.822137  0.071100 -0.986707   
2018-07-31  0.492939  0.912310  0.664738 -0.181202 -0.710470  2.205671   
2018-08-01 -0.167045 -1.021262 -0.412716 -1.387462  0.000000 -1.352030   
...              ...       ...       ...       ...       ...       ...   
2020-08-19 -0.416374 -0.287312 -0.281268 -1.146968 -0.040649 -0.260587   
2020-08-20  0.311358 -0.352173  1.244400 -2.158674 -0.935335 -0.535593   
2020-08-21  0.354737 -0.578316 -0.442475 -0.634305 -0.205262  0.407135   
2020-08-24  1.013319  1.761190  1.218107  2.747710  2.385852  1.805111   
2020-08-25  0.349928 -0.396952  0.943239 -1.404641  0.281234 -0.128481   
2020-08-26  1.002558  1.052127  3.415504 -2.109591 -0.480766  0.051445   
2020-08-27  0.218658 -0.268177 -1.215144  0.195913  1.690818  0.360045   
2020-08-28  0.645939  1.186336  0.236552  1.787702  0.395890  0.948112   
2020-08-31 -0.362253 -1.531967 -0.471994 -2.167939 -1.182973 -1.243820   
2020-09-01  0.941858  2.809974  0.822004 -0.673220  0.279326  1.015294   
2020-09-02  1.446402  2.269921  2.132329 -0.480078  1.432557  1.653945   
2020-09-03 -3.441433 -2.763102 -3.392691 -0.737806 -1.530013 -2.803499   
2020-09-04 -0.816474  0.062108 -1.827426 -0.314464  0.756973  0.231773   
2020-09-08 -2.732292 -1.877717 -2.638390 -3.642107 -2.570185 -1.875640   
2020-09-09  1.974742  2.577889  1.197000  0.684533  1.014610  1.544905   
2020-09-10 -1.736372 -0.940485 -1.478557 -3.665383 -1.406187 -1.276432   
2020-09-11  0.050912  1.276261 -0.316830  0.092041  0.692743  1.358243   
2020-09-14  1.317125  1.444607  0.384745  0.766410  1.375962  1.352921   
2020-09-15  0.505240  0.484770  1.783043 -0.730146 -1.357287  0.063553   
2020-09-16 -0.396866  0.075382 -1.080558  4.014706  1.133147  1.016393   
2020-09-17 -0.879520  0.738182 -1.837136  0.147318 -1.040422  0.201229   
2020-09-18 -1.151271 

In [156]:
def opt_w(rho,Q):
    n = len(rho)
    bnds = sco.Bounds(0,1,keep_feasible=True)
    w0 = n*[1/n]
    cons = ({'type':'eq','fun':lambda x: np.sum(x)-1})
    def obj(x):
        return -x.T.dot(rho)+x.T.dot(Q.dot(x))
    result = sco.minimize(obj,w0,method='SLSQP',constraints=cons,bounds=bnds)
    return result.x

### Optimization function
    calculates optimal weights
    rho is vector of returns
    Q is covariance matrix
    wp is the previous allocation
    lam is the rebalancing penalty
    B_r is the vector of betas
    B_t is the target beta

In [157]:
def opt_w2(rho,Q,wp,lam,B_r,B_t):
    n = len(rho)
    bnds = sco.Bounds(0,1,keep_feasible=True)
    w0 = n*[1/n]
    cons = ({'type':'eq','fun':lambda x: np.sum(x)-1},
            {'type':'eq','fun':lambda x: np.dot(B_r,x)-B_t})
    def obj(x):
        return -x.T.dot(rho)+lam*(x-wp).T.dot(Q.dot(x-wp))
    result = sco.minimize(obj,w0,method='SLSQP',constraints=cons,bounds=bnds)
    return result.x

In [158]:
# Betas vector
hist_covs = np.array(df_full.cov().iloc[0])
spy_var = hist_covs[0]
beta_vec = hist_covs[1:]/spy_var
pd.DataFrame({'Sector':sec_names, 'Beta':beta_vec})

Sector      Beta
0    Mats  1.035061
1    Coms  0.959627
2    Enrg  1.296502
3     Fin  1.175039
4    Indu  1.088327
5    Tech  1.192253
6   ConsS  0.691918
7   ReEst  0.935377
8    Util  0.790266
9    Hlth  0.846778
10  ConsD  0.993106

In [159]:
df = df_full.iloc[:,1:]
recalc_Q = df.cov()
recalc_rets = np.array(df.mean(0))
lam = 5
wp = np.array([1/len(df.columns)]*len(df.columns))
B_t = 1.25

In [160]:
temp = opt_w(recalc_rets,recalc_Q)
temp

array([4.74330819e-16, 7.53951451e-02, 0.00000000e+00, 1.54410535e-16,
       0.00000000e+00, 0.00000000e+00, 7.68712237e-01, 3.80142004e-16,
       0.00000000e+00, 1.55892618e-01, 0.00000000e+00])

In [161]:
temp = opt_w2(recalc_rets, recalc_Q, wp, lam, beta_vec, B_t)
temp

array([0.00000000e+00, 6.10622664e-16, 5.53934687e-01, 1.22263311e-14,
       0.00000000e+00, 4.46065313e-01, 7.92421684e-15, 0.00000000e+00,
       0.00000000e+00, 7.41073869e-15, 0.00000000e+00])

In [162]:
df.reset_index(inplace=True)
df['Day'] = df.Date.apply(lambda x: x.day)
df['Rebalance'] = np.where(df.Day.shift(1) > df.Day, 1, 0)
df.head()

/Users/Brendon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Brendon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy



Date       XLB       XLC       XLE       XLF       XLI       XLK  \
0 2018-06-20 -0.324852  1.241020  0.441556 -0.255934  0.068273  0.209968   
1 2018-06-21 -1.063447 -0.612904 -1.851644 -0.293263 -1.255467 -0.768355   
2 2018-06-22  1.456308  0.437648  1.995152 -0.477932  0.345500 -0.323806   
3 2018-06-25 -1.555041 -2.059809 -2.009327 -1.071296 -1.267041 -2.076252   
4 2018-06-26  0.381873  0.165814  1.262920 -0.336088  0.376603  0.403848   

        XLP      XLRE       XLU       XLV       XLY  Day  Rebalance  
0  0.097916  1.079360  0.079694  0.212105  0.474145   20          0  
1  0.195649  0.596730  0.338456 -0.576213 -0.712315   21          0  
2  0.820151  0.874177  0.694438  0.449467 -0.170393   22          0  
3  0.503583 -0.247601  1.655168 -0.918412 -2.173909   25          0  
4 -0.423972  0.527473  0.116309 -0.308978  0.716253   26          0

In [163]:
n = len(ticks)-1
w1 = w2 = w3 = np.array(n*[1/n])
lam, B_t = 5,1
w1_returns, w2_returns, w3_returns = [], [], [] 
w1s, w2s, w3s = w1, w2, w3
for i in range(0,len(df)):
    if df.Rebalance[i] == 1:
        temp = df_full.iloc[0:i,1:]
        hist_covs = np.array(df_full.iloc[0:i,:].cov().iloc[0])
        spy_var = hist_covs[0]
        beta_vec = hist_covs[1:]/spy_var
        recalc_Q = temp.cov()
        recalc_rets = np.array(temp.mean(0))
        w1 = opt_w(recalc_rets,recalc_Q)
        w1s = np.append(w1s, w1, axis=0)
        w2 = opt_w2(recalc_rets, recalc_Q, w2, lam, beta_vec, B_t)
        w2s = np.append(w2s, w2, axis=0)
        w3 = rg.uniform(0,1,n)
        w3 = w3/sum(w3)
        w3s = np.append(w3s, w3, axis=0)
    w1_returns.append(w1.T.dot(df_full.iloc[i,1:]))
    w2_returns.append(w2.T.dot(df_full.iloc[i,1:]))
    w3_returns.append(w3.T.dot(df_full.iloc[i,1:]))
    
sum(w1_returns), sum(w2_returns), sum(w3_returns), sum(df_full['SPY'])

(23.90098997301394, 34.20783750729561, 24.372276960368676, 31.06499532336833)

In [164]:
trace0 = go.Scatter(
    x = df.Date, y = np.cumsum(w1_returns), name = 'Portfolio 1'
)
trace1 = go.Scatter(
    x = df.Date, y = np.cumsum(w2_returns), name = 'Portfolio 2'
)
trace2 = go.Scatter(
    x = df.Date, y = np.cumsum(w3_returns), name = 'Random Portfolio'
)
trace3 = go.Scatter(
    x = df.Date, y = np.cumsum(df_full['SPY']), name = 'SPY'
)
data = [trace0,trace1,trace2,trace3]
layout = go.Layout(
    title = 'Portfolios vs SPY', yaxis = dict(title = 'Cumulative Return (%)'))
fig = go.Figure(data=data, layout=layout)
plotly.offline.iplot(fig)

In [141]:
returns = np.array((sum(w1_returns), sum(w2_returns), sum(w3_returns), sum(df_full['SPY'])))
volatility = np.sqrt(252)*np.array((np.std(w1_returns),np.std(w2_returns),np.std(w3_returns),np.std(df_full['SPY'])))
results = pd.DataFrame({'Portfolio': ['Portfolio 1', 'Portfolio 2', 'Random', 'SPY'], 
              'Return (%)': returns, 'Vol (%)': volatility, 'Sharpe': returns/volatility})
results.set_index('Portfolio')

Return (%)    Vol (%)    Sharpe
Portfolio                                   
Portfolio 1   24.158685  22.026109  1.096820
Portfolio 2   34.540396  25.458812  1.356717
Random        21.118711  25.405540  0.831264
SPY           31.489222  24.477141  1.286475

In [169]:
np.split(w1s,len(w1s)/11)

[array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
        0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
        0.09090909]),
 array([1.75152431e-16, 3.42518282e-16, 2.18064721e-03, 0.00000000e+00,
        2.10591871e-16, 0.00000000e+00, 0.00000000e+00, 5.29594042e-01,
        4.68225311e-01, 3.04590462e-16, 0.00000000e+00]),
 array([0.00000000e+00, 0.00000000e+00, 7.74942775e-02, 3.26569974e-01,
        1.40631653e-17, 6.63948830e-17, 2.47783696e-01, 5.08685595e-02,
        2.97283493e-01, 1.88502104e-17, 3.33360373e-17]),
 array([0.00000000e+00, 3.44319797e-17, 1.37523355e-02, 2.20019848e-01,
        5.00839431e-17, 2.27608516e-17, 4.92480892e-17, 5.13478042e-02,
        3.31883669e-01, 3.82996343e-01, 0.00000000e+00]),
 array([0.00000000e+00, 8.08711003e-17, 5.38351894e-02, 1.43184257e-01,
        0.00000000e+00, 0.00000000e+00, 8.24808063e-02, 0.00000000e+00,
        2.25286617e-01, 4.36612568e-01, 5.86005615e-02]),
 array([1.14414739e-17, 0.00000000